### ISSUE TITLE
SIW13 dataset files

### ISSUE THREAD

**Issue by stesteau** [lluisgomez/script_identification#1]
Hello,

Where can I find the SIW13 dataset files? I have searched for them in vain.

Thank you!

**Comment by stesteau** [comment]
http://mc.eistar.net/~xbai/mspnProjectPage/

**Comment by lluisgomez** [comment]
http://mclab.eic.hust.edu.cn/~xbai/mspnProjectPage/

**Comment by liepieshov** [comment]
@moskiteau @lluisgomez hey guys, where can I find this dataset? The link doesn't work
