### ISSUE TITLE
 Unknown bottom blob 'group_data' (layer 'slice_group', bottom index 0)

### ISSUE THREAD

**Issue by Actasidiot** [lluisgomez/script_identification#3]
Hi lluisgomez:
excellent work.
when i ran your code for finetuning ECN:
"/path_to_caffe/build/tools/caffe train --solver=caffe_models/siw13_ECNx10_5_3_3_1/solver.prototxt --weights=caffe_models/siw13_simple_5_3_3_1/siw13_simple_5_3_3_1_train_iter_110000.caffemodel"
i got the error：
 Unknown bottom blob 'group_data' (layer 'slice_group', bottom index 0)
i cannot figure out the problem.

**Comment by lluisgomez** [comment]
@KawhiWang the 'group_data' blob is defined on the input layer of caffe_models/siw13_ECNx10_5_3_3_1/train_val.prototxt in [L5](https://github.com/lluisgomez/script_identification/blob/master/ECN/caffe_models/siw13_ECNx10_5_3_3_1/train_val.prototxt#L5) 

I do not see a reason for this error unless you have modified the prototxt

**Comment by Actasidiot** [comment]
Thank you for your reply.
I solved the problem by removing "test_iter: 1000 test_interval: 1000" from solver.prototxt
I guess the reason is that I was using the new version Caffe .
